# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria', models.CharField(max_length=50)),
                ('lista_verificacion', models.TextField()),
                ('observacion', models.CharField(max_length=300, null=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_audit', to='personal.Personal')),
                ('auditor_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_lider', to='personal.Personal')),
            ],
        ),
    ]
