# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(null=True)),
                ('personal_disponible', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('tipo_proceso', models.CharField(max_length=20, null=True)),
                ('fec_ingresa', models.DateTimeField(blank=True, null=True)),
                ('fec_modifica', models.DateTimeField(blank=True, null=True)),
                ('usuario_ing_id', models.IntegerField(blank=True, null=True)),
                ('usuario_mod_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(null=True)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimiento', to='areas.Area_Proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=150)),
                ('docfile', models.FileField(max_length=200, null=True, upload_to=b'')),
                ('url_carpeta', models.CharField(max_length=300, null=True)),
                ('tipo_proceso', models.CharField(max_length=1, null=True)),
                ('disponible', models.CharField(max_length=1, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('fec_ingresa', models.DateTimeField(blank=True, null=True)),
                ('fec_modifica', models.DateTimeField(blank=True, null=True)),
                ('usuario_ing_id', models.IntegerField(blank=True, null=True)),
                ('usuario_mod_id', models.IntegerField(blank=True, null=True)),
                ('estado_colaborador', models.CharField(default=0, max_length=1)),
                ('estado_encargado', models.CharField(default=0, max_length=1)),
                ('observaciones_encargado', models.CharField(max_length=100, null=True)),
                ('estado_lider', models.CharField(default=0, max_length=1)),
                ('observaciones_lider', models.CharField(max_length=100, null=True)),
                ('estado_admin', models.CharField(default=0, max_length=1)),
                ('observaciones_admin', models.CharField(max_length=100, null=True)),
                ('id_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Areas')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='id_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='area_proceso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Areas'),
        ),
        migrations.AddField(
            model_name='area_proceso',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='area_proceso',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Procesos'),
        ),
    ]
