# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_proceso',
            name='rol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
