# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-21 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20190221_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesos',
            name='docfile',
        ),
    ]
