# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.IntegerField()),
                ('indicador', models.CharField(max_length=50)),
                ('signo', models.CharField(max_length=1)),
                ('operacion', models.IntegerField()),
                ('ponderacion', models.CharField(max_length=50, null=True)),
                ('periodos', models.IntegerField(null=True)),
                ('meta', models.IntegerField()),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('estado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
