# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_auto_20190313_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Objetivos'),
        ),
    ]
