# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-14 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20190313_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivos',
            name='meta_fin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objetivos',
            name='meta_inicio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Objetivos'),
        ),
    ]
