# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_auto_20190314_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Departamentos')),
            ],
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
