# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_responsables'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsables',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
