# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sac',
            name='sac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sac_anterior', to='sac.Sac'),
        ),
    ]
