# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(default=1, max_length=1)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(default=1, max_length=1)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('celular', models.CharField(max_length=10, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.CharField(default=1, max_length=1, null=True)),
                ('firma', models.FileField(max_length=200, null=True, upload_to=b'')),
                ('id_areapersonal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.AreaPersonal')),
                ('id_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='personal.Cargo')),
            ],
        ),
    ]
