# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Normas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('docfile', models.FileField(null=True, upload_to='normas/')),
                ('estado', models.CharField(max_length=1)),
                ('fec_ingresa', models.DateTimeField(blank=True, null=True)),
                ('fec_modifica', models.DateTimeField(blank=True, null=True)),
                ('usuario_ing_id', models.IntegerField(blank=True, null=True)),
                ('usuario_mod_id', models.IntegerField(blank=True, null=True)),
                ('auditor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoClausula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Areas')),
                ('id_clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normas.Clausulas')),
                ('id_norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normas.Normas')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Procesos')),
            ],
        ),
        migrations.AddField(
            model_name='clausulas',
            name='id_norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normas.Normas'),
        ),
    ]
