# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Areas')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Procesos')),
            ],
        ),
    ]
